services:
  - type: web
    name: tl-lsg-app
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tl-lsg-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: reports@yourdomain.com
      - key: SENDGRID_FROM_NAME
        value: T&L LSG Reports
      - key: SITE_URL
        value: https://tl-lsg-app.onrender.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false

databases:
  - name: tl-lsg-db
    plan: starter

